import Quiz from '@/components/Quiz';
import Head from 'next/head'
import { useEffect, useState } from 'react';

export default function Home() {

  const [quiz, setQuiz] = useState([])
  const [options, setOptions] = useState([])
  const [score, setScore] = useState(0)

  useEffect(() => {
    fetchData()
  }, [])


  async function fetchData() {
    try {
      const response = await fetch(
        "https://opentdb.com/api.php?amount=5&type=multiple&category=18"
      );
      const data = await response.json();

      let quizArr = [];
      let allOptionsArr = []

      data.results.map((obj, idx) => {
        // console.log(obj);
        const randomNum = Math.floor(Math.random() * 4);
        obj.incorrect_answers.splice(randomNum, 0, obj.correct_answer);

        quizArr.push({
          id: idx,
          question: obj.question
            .replace(/&#039;/g, "'").replace(/&#62;/g, ">").replace(/&#60;/g, "<").replace(/&apos;/g, "'").replace(/&amp;/g, "&")
            .replace(/&quot;/g, '"')
            .replace(/&apos;/g, "'")
            .replace(/&gt;/g, ">")
            .replace(/&lt;/g, "<")
            ,
          options: obj.incorrect_answers,
          correct_answer: obj.correct_answer,
        });
      });
      setQuiz(quizArr);
      setOptions(allOptionsArr);
    } catch (err) {
      console.log(err);
    }
  }

  // setInterval( () =>  console.log(correctAnswers), 1000)

  function resetGame() {
    fetchData()
    setScore(0)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Quiz quizArr={quiz} allOptions={options} score={score} setScore={setScore} resetGame={resetGame} />
          {/* <button
            onClick={() => fetchData()}
            type="button" className="my-4 mx-3 inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out">Reset Game</button> */}
        </div>
      </main>
    </>
  )
}
